config:
  credentials:
    oeg:
      password: 9rScwwFGLZDNfGz
      username: jaime.vrivera
    pinecone:
      key: 37e3270d-6a15-4756-905e-51d6583c65a8
      indexname: oeg-testing
  options:
    new: False
  paths:
    driver: /bin/geckodriver.exe
  embedder:
    old: nomic-embed-text-v1.5
    new: jina/jina-embeddings-v2-base-es
  model:
    modelname: meta-llama-3.1-8b-instruct
    host: http://localhost:1234/v1
    api_key: lm-studio