config:
  credentials:
    oeg:
      username: username
      password: password
    pinecone:
      key: key
      indexname: name
  options:
    new: False
    eval: True
  paths:
    driver: driver-path
    libreoffice: libreoffice-path
  embedder:
    old: nomic-embed-text
    new: jina/jina-embeddings-v2-base-es
  model:
    modelname: mistral