config:
  credentials:
    oeg:
      password: password
      username: username
    pinecone:
      key: key
      indexname: oeg-testing
  options:
    new: False
  paths:
    driver: /bin/geckodriver.exe
    libreoffice: 
  embedder:
    old: nomic-embed-text-v1.5
    new: jina/jina-embeddings-v2-base-es
  model:
    modelname: meta-llama-3.1-8b-instruct
    host: http://localhost:1234/v1
    api_key: lm-studio