config:
  credentials:
    oeg:
      username: username
      password: password
    pinecone:
      key: key
      indexname: oeg-testing
  options:
    new: False
  paths:
    driver: driver-path
    libreoffice: libreoffice-path
  embedder:
    old: nomic-embed-text-v1.5
    new: jina/jina-embeddings-v2-base-es
  model:
    modelname: meta-llama-3.1-8b-instruct
    modelnamellama: mistral
    host: http://127.0.0.1:1234
    api_key: lm-studio